name: Upload Website

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Sync the local directory with the S3 bucket
    - name: Sync website to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete  # Set public read for website
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}   # Your S3 bucket name
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   # AWS Access Key from Secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Key from Secrets
        AWS_REGION: 'us-east-1'  # Your AWS region
        SOURCE_DIR: 'website'  # Directory to upload (ensure 'website' is the correct path)

